name: "units-test"
on:
  pull_request:
  push:
    branches:

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm ci
    - run: npm test

  simple-integration-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: npm ci
    - uses: ./
      with:
        files: example-env/simple/env.yaml
    - name: Check action returns correct value for environment variable
      run: |
        if [[ $WEBSERVER_URL =~ "www.example.com" ]]; then
          echo "Pass"
        else
            echo "Test failed: output was not 'www.example.com'"
            exit 1
        fi
